
<link href="common/themes/default/style.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="common/themes/css/core.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="common/themes/css/print.css" rel="stylesheet" type="text/css" media="print"/>

<script src="common/jsFile/jquery/jquery-1.8.3.js" type="text/javascript"></script>
<script src="common/jsFile/jqueryPlugin/jquery.cookie.js" type="text/javascript"></script>
<script src="common/jsFile/jqueryPlugin/jquery.validate.js" type="text/javascript"></script>
<script src="common/jsFile/jqueryPlugin/jquery.bgiframe.js" type="text/javascript"></script>

<script src="common/jsFile/dwz/dwz.core.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.util.date.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.validate.method.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.regional.zh.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.barDrag.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.drag.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.tree.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.accordion.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.ui.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.theme.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.switchEnv.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.alertMsg.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.contextmenu.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.navTab.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.tab.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.resize.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.dialog.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.dialogDrag.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.sortDrag.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.cssTable.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.stable.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.taskBar.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.ajax.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.pagination.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.database.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.datepicker.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.effects.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.panel.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.checkbox.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.history.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.combox.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.print.js" type="text/javascript"></script>
<script src="common/jsFile/dwz/dwz.regional.zh.js" type="text/javascript"></script>

<script src="common/jsFile/jf/jf.core.js" type="text/javascript"></script>